fix: allow direct return of required-await-functions
square/eslint-plugin-square pull request #564
Opened 2022-01-19 22:29 UTC by fengb

This change allows for direct `return requiredAsyncFunc()`

Otherwise it conflicts with "no-return-await" rule of disallowing `return await requiredAsyncFunc();`

2022-01-19 22:49 UTC, bmish commented on tests/lib/rules/require-await-function.js
> +  },
It seems like we're missing some tests around nesting:

```
function myFunction() { return foo(asyncFunc()); }
```

```
function myFunction() { foo(asyncFunc()); }
```

2022-01-20 15:08 UTC, bmish commented on tests/lib/rules/require-await-function.js
> +    code: 'async function test() { foo(asyncFunc()); }',
I thought this should be a valid test case, since someone might want to pass around the promise when calling the function inside another function call.

2022-01-20 15:12 UTC, fengb commented on tests/lib/rules/require-await-function.js
> +    code: 'async function test() { foo(asyncFunc()); }',
Good point

2022-01-20 16:36 UTC, bmish commented on docs/rules/require-await-function.md
On line 11, there's a typo, I think it should say `await` not `async`, would you mind fixing that?

2022-01-20 16:38 UTC, bmish commented on lib/rules/require-await-function.js
> +function isAwaitOrReturnCall(node, isPromiseChain = false) {
Can we avoid touching `isAwaitCall`? I think this is complicating the code by making this function do too many things. Shouldn't we just have one function for checking await and one function for checking return?

2022-01-21 01:58 UTC, bmish requested changes

2022-01-21 01:58 UTC, bmish commented on lib/rules/require-await-function.js
> +function isNestedCall(node, isPromiseChain = false) {
no longer need `isPromiseChain`?

2022-01-21 03:45 UTC, fengb commented on lib/rules/require-await-function.js
> +function isNestedCall(node, isPromiseChain = false) {
It's used on line 72. The main problem is that `func().then(() => {})` reports "CallExpression" as the node's grandparent, which isn't a nested call.

I don't like this code but not sure how else to clean it up.

2022-01-21 14:49 UTC, bmish approved these changes
Can you fix linting?

2022-01-21 16:22 UTC, bmish commented
Thanks!

2022-01-21 16:22 UTC, merged