Update no-translation-key-interpolation to check for directly imported `t` method. Add option `enforceStringLiteralKeys`
square/eslint-plugin-square pull request #598
Opened 2022-02-28 17:16 UTC by edcheung1

2022-02-28 17:41 UTC, bmish commented
Can we split this into two PRs? Bugs fixes and new options should be separate PRs.

2022-02-28 17:44 UTC, edcheung1 commented
> Can we split this into two PRs? Bugs fixes and new options should be separate PRs.

Sure thing, let me split this up

2022-02-28 17:59 UTC, bmish requested changes

2022-02-28 17:59 UTC, bmish commented on lib/rules/no-translation-key-interpolation.js
> +function isT(node) {
Checking for any function named `t` is going to have too many false positives. We actually need to check imports too.

```js
import { t } from 'intl';
import { t } from 'i18n'; // when using custom service name
import { t as foo } from 'intl';
```

In eslint-plugin-ember, there are a bunch of examples of lint rules that check imports: https://github.com/ember-cli/eslint-plugin-ember/blob/master/lib/rules/no-pause-test.js

2022-02-28 18:06 UTC, edcheung1 commented on lib/rules/no-translation-key-interpolation.js
> +function isT(node) {
It looks like this util does a lot of the source module identification. Is there a way to import/reference this, or do you suggest just copying it in?

https://github.com/ember-cli/eslint-plugin-ember/blob/master/lib/utils/import.js

2022-02-28 18:11 UTC, edcheung1 commented on lib/rules/no-translation-key-interpolation.js
> +function isT(node) {
Ah nevermind, I see there's some to `node.specifiers`. Let me see if I can incorporate that to check with `serviceName`

2022-02-28 22:23 UTC, bmish commented on lib/rules/no-translation-key-interpolation.js
> +function isT(node) {
Can we copy over the import helpers from eslint-plugin-ember? Checking imports is very common and something we should probably be doing in other rules too.

2022-02-28 22:37 UTC, alecrios commented on lib/rules/no-translation-key-interpolation.js
> +      DEFAULT_SERVICE_NAME;
Can we use [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)?

2022-02-28 22:39 UTC, bmish commented on lib/rules/no-translation-key-interpolation.js
> +      DEFAULT_SERVICE_NAME;
Not quite yet since we still support Node 12.

2022-03-01 00:51 UTC, edcheung1 commented on lib/rules/no-translation-key-interpolation.js
> +function isT(node) {
Done. Copied over `import.js` and corresponding tests and utils

2022-03-02 19:16 UTC, bmish requested changes

2022-03-02 19:16 UTC, bmish commented on .babelrc
> +}
Files should end in newline.

```suggestion
}

```

2022-03-02 19:16 UTC, bmish commented on lib/utils/is-identifier.js
> +  if (node !== undefined && node.type === 'Identifier') {
This isn't right. It could skip the `name` check. Why do we need to change this function? Even better, avoid using this function.

2022-03-02 19:16 UTC, bmish commented on lib/utils/is-import-declaration.js
> +function isImportDeclaration(node) {
Let's avoid adding this helper. My goal is to move away from having these trivial helpers that only check the type.

2022-03-02 19:16 UTC, bmish commented on lib/utils/is-call-expression.js
> +function isCallExpression(node) {
Let's avoid adding this helper. My goal is to move away from having these trivial helpers that only check the type.

2022-03-02 19:16 UTC, bmish commented on lib/rules/no-translation-key-interpolation.js
> +          importedTranslationServiceName = node.source.value;
We can't assume any import we see that has a source is the translation service import. Check eslint-plugin-ember to see the proper way to use these import helpers.

2022-03-02 19:16 UTC, bmish commented on lib/rules/no-translation-key-interpolation.js
> +    importedTranslationServiceName === serviceName &&
This check should not be part of this function. `importedTranslationMethodName` which is checked a few lines later should only be set if it's imported from the right place.

2022-03-02 19:16 UTC, bmish commented on lib/utils/import.js
> +'use strict';
Can you add a comment at the top of this file with a link to the eslint-plugin-ember file that this is based on.

2022-03-02 19:44 UTC, edcheung1 commented on lib/rules/no-translation-key-interpolation.js
> +          importedTranslationServiceName = node.source.value;
That's true. I'll move the assignment inside the conditional like here:

https://github.com/ember-cli/eslint-plugin-ember/blob/509e71171505f899cba64861373bbedf941b9f14/lib/rules/no-pause-test.js#L38-L39

2022-03-02 19:48 UTC, edcheung1 commented on lib/rules/no-translation-key-interpolation.js
> +    importedTranslationServiceName === serviceName &&
Makes sense. I removed `let importedTranslationMethodName = DEFAULT_METHOD_NAME;` so that `importedTranslationMethodName` won't default to anything and will only be set if the import matches the `serviceName` from above

2022-03-02 20:32 UTC, edcheung1 commented on lib/rules/no-translation-key-interpolation.js
> +          importedTranslationServiceName = node.source.value;
Actually nevermind, I don't need to use `importedTranslationServiceName` if I just rely on checking whether `importedTranslationMethodName` has been set

2022-03-02 20:32 UTC, edcheung1 commented on lib/utils/is-identifier.js
> +  if (node !== undefined && node.type === 'Identifier') {
I added a test that was missing from `eslint-plugin-ember` in order to reach this code path, which required passing in an `undefined` node:

https://github.com/ember-cli/eslint-plugin-ember/blob/master/lib/utils/import.js#L45-L49

The previous code didn't have a guard against `undefined` node before `node.type`. I see where my change is wrong and adjusted to perform name validation if `name` is passed in, otherwise return `true`

As for whether we need this function, it seems the `isMemberExpression` is relying on being able to pass in the `name` parameter to perform the additional check. It seems to have forked from the original `isIdentifier` method from `eslint-plugin-ember`

https://github.com/square/eslint-plugin-square/blob/master/lib/utils/is-member-expression.js#L25-L26
https://github.com/ember-cli/eslint-plugin-ember/blob/509e71171505f899cba64861373bbedf941b9f14/lib/utils/types.js#L216

2022-03-02 20:49 UTC, bmish requested changes

2022-03-02 20:49 UTC, bmish commented on lib/rules/no-translation-key-interpolation.js
> +          importedTranslationMethodName = getImportIdentifier(
We need an `||` in here in case there are multiple import statements importing from the same source.

```
importedTranslationMethodName =  importedTranslationMethodName || getImportIdentifier(...)
```


In case someone had something like this:

```js
import { t } from 'i18n';
import { foo } from 'i18n';
```

This is the same thing we do in eslint-plugin-ember. Not my favorite API for these import helpers, but it works.

2022-03-02 20:49 UTC, bmish commented on lib/rules/no-translation-key-interpolation.js
> +function isT(node, serviceName, importedTranslationMethodName) {
`serviceName` isn't used

2022-03-02 20:49 UTC, bmish commented on lib/utils/is-identifier.js
> +  if (node !== undefined && node.type === 'Identifier') {
If we have to check for undefined, can we just use an early return:
```js
if (!node) {
  return false;
}

2022-03-02 21:01 UTC, edcheung1 commented on lib/rules/no-translation-key-interpolation.js
> +          importedTranslationMethodName = getImportIdentifier(
Gotcha, added `||`. Thanks for the call out!

2022-03-02 21:18 UTC, bmish requested changes
A few more comments. I'd also recommend testing this update by running it on an existing codebase just to see if the violations are correct.

2022-03-02 21:18 UTC, bmish commented on lib/rules/no-translation-key-interpolation.js
> +          if (node.arguments[0].type === 'TemplateLiteral') {
Can we combine this nested if statement with the outer one?

2022-03-02 21:18 UTC, bmish commented on lib/utils/is-identifier.js
> +  if (node !== undefined && node.type === 'Identifier') {
Ping ^

2022-03-02 21:18 UTC, bmish commented on tests/helpers/faux-context.js
> +'use strict';
Since this file is pretty obscure, can you also add the comment about where it comes from in eslint-plugin-ember?

2022-03-02 21:18 UTC, bmish commented on tests/helpers/faux-context.js
> + * expected by `getSourceModuleNameForIdentifier` and `isEmberCoreModule`
`isEmberCoreModule` isn't in this package so let's no mention it.

2022-03-02 21:40 UTC, edcheung1 commented on lib/rules/no-translation-key-interpolation.js
> +          if (node.arguments[0].type === 'TemplateLiteral') {
Done

2022-03-02 21:41 UTC, edcheung1 commented on tests/helpers/faux-context.js
> +'use strict';
Yep, added comment

2022-03-02 21:41 UTC, edcheung1 commented on tests/helpers/faux-context.js
> + * expected by `getSourceModuleNameForIdentifier` and `isEmberCoreModule`
Removed

2022-03-02 21:44 UTC, edcheung1 commented
> A few more comments. I'd also recommend testing this update by running it on an existing codebase just to see if the violations are correct.

Let me try verifying with `yarn link`

2022-03-02 22:53 UTC, edcheung1 commented
Tested in existing codebase with `yarn link eslint-plugin-square` with new `.eslintrc` rule:

`"square/no-translation-key-interpolation": ["error", { "serviceName": "i18n" }]`

Verified `t()` with interpolated keys are being flagged 🎉

2022-03-02 22:55 UTC, edcheung1 commented
Not sure why the CI builds are failing...is it because I used the latest versions?

```
    "@babel/eslint-parser": "^7.17.0",
    "@babel/plugin-proposal-class-properties": "^7.16.7",
    "@babel/plugin-proposal-decorators": "^7.17.2",
```

I can downgrade it to match eslint-plugin-ember if necessary:

```
    "@babel/eslint-parser": "^7.15.8",
    "@babel/plugin-proposal-class-properties": "^7.13.0",
    "@babel/plugin-proposal-decorators": "^7.15.8",
```

2022-03-03 14:41 UTC, bmish commented
@edcheung1 we should use the latest versions. But you need to temporarily remove the Square-specific artifactory config from `~/.npmrc` and then redo the yarn.lock changes so that we don't end up with Square-internal artifactory URLs.

2022-03-03 17:40 UTC, bmish requested changes

2022-03-03 17:40 UTC, bmish commented on lib/utils/is-import-declaration.js
> +function isImportDeclaration(node) {
Ping...I still see it

2022-03-03 17:40 UTC, bmish commented on lib/utils/is-call-expression.js
> +function isCallExpression(node) {
Ping

2022-03-03 17:42 UTC, edcheung1 commented
Sorry ran into some git issues, should be cleaned up now 🙏

2022-03-03 17:43 UTC, bmish approved these changes
Thank you!

2022-03-03 17:44 UTC, merged

2022-03-03 17:46 UTC, bmish commented
@edcheung1 do you want this released now or do you want to get other changes in too?

2022-03-03 17:47 UTC, edcheung1 commented
I would also like to add the feature to enforce string literals. I can make a new PR

2022-03-03 18:09 UTC, edcheung1 commented
New PR for `enforceStringLiteralKeys`: https://github.com/square/eslint-plugin-square/pull/600