Add enforceStringLiteralKeys option to no-translation-key-interpolation
square/eslint-plugin-square pull request #600
Opened 2022-03-03 18:05 UTC by edcheung1

## Description

Allows users to enforce stricter rules on translation keys by only allowing string literals as keys. Previously, rule would allow keys that are functions or variables.

## Testing
`yarn test`  
`yarn eslint .`

2022-03-03 18:12 UTC, bmish commented
1. Can you explain some more of the motivation for why someone would want this stricter option?
2. Can you check some existing codebases (e.g. Square Dashboard) to find out what scenarios people currently pass functions or variables? Are these usages justified? Would it be easy for them to migrate to string literals?
3. If we add this option, should we enable it by default in the next major version as a breaking change?

2022-03-03 18:57 UTC, edcheung1 commented
> 1. Can you explain some more of the motivation for why someone would want this stricter option?
> 2. Can you check some existing codebases (e.g. Square Dashboard) to find out what scenarios people currently pass functions or variables? Are these usages justified? Would it be easy for them to migrate to string literals?
> 3. If we add this option, should we enable it by default in the next major version as a breaking change?

1. For our team's use case, we want to eliminate all forms of dynamic translation keys. We're often asked where a translation key is used and it can be difficult to grep for a dynamic key. We're also trying to remove unused translations and forcing string literal keys will make it easier for us to audit and clean up unused keys. As an example, there may be cases like:
```
t(`weekday.${dayOfWeek}`);
t(dayOfWeek);
t(getDayOfWeek(day));
```
  While the current rule would catch explicit attempts to break up and dynamic generate a key like in the first case, we want to avoid the keys being obfuscated behind variables or methods as well. I can slack you a doc containing our investigations and motivations if you would like.

2. Looking through Dashboard and Appointments, I see instances like `t(translationKey)` or `t(this._getFreqMonthText(...))` and many more (hundreds?). In a cursory look, many of these can be refactored into a `switch` statement that returns the translation directly, but would be a pretty big effort due to the sheer number of these occurences.

3. I would not enable this by default, and let teams enable this option if they have the bandwidth to perform the refactoring.

2022-03-03 19:21 UTC, bmish requested changes
One comment. And would you like a release after this is merged?

2022-03-03 19:21 UTC, bmish commented on docs/rules/no-translation-key-interpolation.md
> +* `boolean` -- `enforceStringLiteralKeys` -- optional override to restrict translation keys to only string literals (default is `false`)
```suggestion
* `boolean` -- `enforceStringLiteralKeys` -- optional override to restrict translation keys to only string literals (when disabled, function calls and variables are allowed) (default is `false`)
```

2022-03-03 19:39 UTC, edcheung1 commented
> One comment. And would you like a release after this is merged?

Yup, a release would be much appreciated 👍

2022-03-03 19:39 UTC, bmish approved these changes
Thank you!

2022-03-03 19:41 UTC, merged

2022-03-03 19:44 UTC, bmish commented
Released: https://github.com/square/eslint-plugin-square/releases/tag/v22.1.0

2022-03-04 16:00 UTC, bmish commented
One follow-up thought to this. I think the current option name is fine, but one alternate name would have been simply `strict` (default false). No action needed, just sharing for the record.

2022-03-04 17:26 UTC, edcheung1 commented
> One follow-up thought to this. I think the current option name is fine, but one alternate name would have been simply `strict` (default false). No action needed, just sharing for the record.

That makes sense, noted for next time! 👍

2022-06-17 04:57 UTC, Gam3356 commented
Check IP