Remove filenames/match-regex in favor of unicorn/filename-case
square/eslint-plugin-square pull request #691
Opened 2022-07-26 20:18 UTC by rachid-square

## Description

Fix for #690: `eslint-plugin-square` currently has two rules that lint file names

## Screenshots

### Using Base Config Before Fix

ESLint reports `unicorn/filename-case` and `filenames/match-regex`

![Before](https://user-images.githubusercontent.com/88404605/181103624-7fee39d4-75d4-4ea3-8f37-6a7386fdb535.png)

### Using Base Config After Fix

ESLint only reports `unicorn/filename-case`

![After](https://user-images.githubusercontent.com/88404605/181103673-cd30144c-3e7f-4d6a-aa9c-41ccd4da642f.png)

### Using React Config After Update

ESLint still reports a filename rule for pascal casing

![React After](https://user-images.githubusercontent.com/88404605/181103811-b480caa9-94cf-4fd4-8cb9-17a8238f16a0.png)

2022-07-26 20:21 UTC, rachid-square commented
@bmish it looks like the [filenames util](https://github.com/square/eslint-plugin-square/blob/master/lib/utils/filenames.js) is no longer being referenced except for the [lib/index](https://github.com/square/eslint-plugin-square/blob/3d5b62515f1500c41d11050147ea7f8e90e96ce0/lib/index.js#L9) file. I assume removing it would be a breaking change. Should I open a different issue to discuss if we still need the filenames util?

2022-07-27 14:10 UTC, bmish requested changes
Thanks for starting on this. I plan to release this as a breaking change since we're switching from one rule to another.

2022-07-27 14:10 UTC, bmish commented on lib/config/base.js
> -const filenames = require('../utils/filenames');
Can you delete the filenames util at this point too? Don't think we'll need it anymore.

2022-07-27 14:10 UTC, bmish commented on lib/config/react.js
>      {
We need to remove `'filenames/match-regex': 'off'` from below as well. Since we never enable it anymore, we don't need to disable it anymore either. And should we replace it with `'unicorn/filename-case': 'off'` in the below override?

2022-07-27 16:21 UTC, rachid-square commented on lib/config/base.js
> -const filenames = require('../utils/filenames');
I left a comment about that. #674 still needs it

2022-07-27 16:25 UTC, rachid-square commented on lib/config/react.js
>      {
Good catch

2022-07-27 16:27 UTC, rachid-square commented on lib/config/react.js
>      {
Fixed

2022-07-27 16:47 UTC, rachid-square commented on lib/config/base.js
> -const filenames = require('../utils/filenames');
#674 does not need it. I removed the filenames util

2022-07-27 16:50 UTC, bmish approved these changes
Thanks for fixing this!

2022-07-27 16:52 UTC, merged